version: 3
tasks:
  prepare:
    cmds:
      - go install
      - go mod tidy

  up:
    cmd: devcontainer up --workspace-folder .

  test:acc:
    env:
      TF_ACC: "1"
    cmd: go test -v ./...

  test:pkg:
    cmd: go test -v ./pkg/...
