version: 3
tasks:
  prepare:
    cmds:
      - go install
      - go mod tidy

  up:
    cmd: devcontainer up --workspace-folder .

  test:provider:
    env:
      TF_ACC: "1"
    vars:
      SCOPE: '{{ len .CLI_ARGS_LIST | eq 0 | ternary "./internal/..." .CLI_ARGS }}'
    cmd: go test -v {{.SCOPE}}

  test:pkg:
    vars:
      SCOPE: '{{ len .CLI_ARGS_LIST | eq 0 | ternary "./pkg/..." .CLI_ARGS }}'
    cmd: go test -v {{.SCOPE}}
